module.exports = {
    registerUser: require('./registerUser'),
    authenticateUser: require('./authenticateUser'),
    retrieveUser: require('./retrieveUser'),
    updateUserAvatar: require('./updateUserAvatar'),
    updateUserPassword: require('./updateUserPassword'),
    createPost: require('./createPost'),
    retrievePosts: require('./retrievePosts'),
    deletePost: require('./deletePost'),
    retrievePost: require('./retrievePost'),
    addCommentToPost: require('./addCommentToPost'),
    removeCommentFromPost: require('./removeCommentFromPost'),
    createPet: require('./createPet'),
    retrievePet: require('./retrievePet'),
    retrievePets: require('./retrievePets'),
    toggleLikePost: require('./toggleLikePost'),
    newReminder: require('./newReminder'),
}
